#!/bin/bash

IP=$1

echo $IP


echo Deploying fib.py to $IP .......
./webrepl/webrepl_cli.py fib.py $IP:/fib.py -p good2cu
echo  deploy fib success...

echo Deploying face.py to $IP .......
./webrepl/webrepl_cli.py face.py $IP:/face.py -p good2cu
echo  deploy face success...


echo Deploying cs.py to $IP .......
./webrepl/webrepl_cli.py cs.py $IP:/cs.py -p good2cu
echo  deploy cs success...

echo Deploying pit.py to $IP .......
./webrepl/webrepl_cli.py pit.py $IP:/pit.py -p good2cu
echo  deploy pit success...


echo Deploying ndn.py to $IP .......
./webrepl/webrepl_cli.py ndn.py $IP:/ndn.py -p good2cu
echo deploy ndn success...


echo Deploying ndn.py to $IP .......
./webrepl/webrepl_cli.py micro-nfd.py $IP:/main.py -p good2cu
echo deploy ndn success...
